### ISSUE TITLE
Modify read_files() to handle a single file

### ISSUE THREAD

**Issue by DJuboor** [lbanawa/photo_filters#6]
**TL;DR:**
Make our read_files() function also work when passing a single files' full path.

**Suggested Tests:**
Success Case:
- [x] input is a single valid image path

**Success criteria:**
- [x] All current tests read_files() tests pass when input is a valid path to a single file
- [x] Additional suggested test is written and also passes

**Comment by lbanawa** [comment]
Ticket resolved: https://github.com/lbanawa/photo_filters/pull/8

**Comment by lbanawa** [comment]
2a07e8d3e5a34f4c1131a54c8e9e3c21e6fd2d0c

merge single file test with success case test, simplify if statements
